import { ApiProperty } from '@nestjs/swagger';
import {
  PrimaryGeneratedColumn,
  Column,
  Entity,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { User } from './User.entity';

@Entity()
export class SMELOAN {
  @ApiProperty({
    required: true,
    description: 'Autogenerated',
  })
  @PrimaryGeneratedColumn('increment')
  id: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
  })
  user_id: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
  })
  business_name: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
  })
  business_address: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: true,
  })
  RC_number: string;

  @ApiProperty({
    required: false,
  })
  @Column({
    nullable: true,
  })
  TIN_number: string;

  @ApiProperty({
    required: true,
    description: 'The number of years the business has be in existence',
  })
  @Column({
    nullable: false,
  })
  business_up_time: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
  })
  purpose_of_loan: string;

  @ApiProperty({
    required: true,
    description: '1 = payday loan, 2 = sme loan',
  })
  @Column({
    nullable: false,
  })
  type: number;

  @ApiProperty({
    required: true,
    description: '1 = pending, 2 = approved, 3 = rejected',
  })
  @Column({
    nullable: false,
    default: 1,
  })
  status: number;

  @ApiProperty({
    required: true,
    description: 'if the sme loan should be saved as draft',
  })
  @Column({
    nullable: false,
    default: true,
  })
  draft: boolean;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
    default: new Date().toISOString(),
  })
  created_at: string;

  @ManyToOne(() => User, (user) => user.SMEloans, {
    cascade: ['insert', 'update', 'remove'],
  })
  @JoinColumn({ referencedColumnName: 'id', name: 'user_id' })
  user: User;
}
