import { ApiProperty } from '@nestjs/swagger';
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class User {
  @ApiProperty({
    required: false,
    description: 'Autogenerated',
  })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    type: String,
    nullable: false,
  })
  email: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
    type: 'varchar',
  })
  firstname: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
    type: 'varchar',
  })
  lastname: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
    type: 'varchar',
  })
  phone: string;

  @ApiProperty({
    required: true,
  })
  @Column({
    nullable: false,
    type: 'varchar',
  })
  password: string;

  @Column({
    default: new Date().toISOString(),
    nullable: false,
  })
  created_at: string;
}
